### ISSUE TITLE
Add .podspec

### ISSUE THREAD

**Issue by mjgallag** [react-native-community/react-native-voice#105]

**Comment by makedirectory** [comment]
require 'json'
version = JSON.parse(File.read('package.json'))["version"]

Pod::Spec.new do |s|
  s.name           = "react-native-voice"
  s.version        = version
  s.summary        = "![alt tag]"
  s.homepage       = "https://github.com/wenkesj/react-native-voice"
  s.license        = "MIT"
  s.author         = "Sam Wenke"
  s.platform       = :ios, "9.0"
  s.source         = { :git => "https://github.com/wenkesj/react-native-voice.git", :tag => "v#{s.version}" }
 s.source_files   = 'ios/Voice/*.{h,m}'
 s.preserve_paths = "**/*.js"
 s.dependency 'React'

end

**Comment by lfoliveir4** [comment]
> require 'json'
> version = JSON.parse(File.read('package.json'))["version"]
> 
> Pod::Spec.new do |s|
> s.name = "react-native-voice"
> s.version = version
> s.summary = "![alt tag]"
> s.homepage = "https://github.com/wenkesj/react-native-voice"
> s.license = "MIT"
> s.author = "Sam Wenke"
> s.platform = :ios, "9.0"
> s.source = { :git => "https://github.com/wenkesj/react-native-voice.git", :tag => "v#{s.version}" }
> s.source_files = 'ios/Voice/_.{h,m}' s.preserve_paths = "**/_.js"
> s.dependency 'React'
> 
> end

@makedirectory Did you solve your problem ?

**Comment by makedirectory** [comment]
Yes this works without any issues

**Comment by Naturalclar** [comment]
Looks like this repository already contains a `.podspec` file.
https://github.com/react-native-community/react-native-voice/blob/master/react-native-voice.podspec
should this issue be closed?

**Comment by mjgallag** [comment]
@Naturalclar great! I’ll close.
