### ISSUE TITLE
Why is this library not published to npm?

### ISSUE THREAD

**Issue by Damnum** [react-native-community/react-native-voice#183]
This library seems to be still active (commits and merged pull requests). Why is it not being published on npm? Last publish is 1 year ago: https://www.npmjs.com/package/react-native-voice

It's a bit of a hassle to fork and publish it myself every time there is a fix.

**Comment by sibelius** [comment]
@wenkesj needs to give me permissions to release a new version on npm

@wenkesj if you give me admin permission I can move this to react-native-community so more people can easily collaborate

**Comment by wenkesj** [comment]
I will give you access this afternoon! Apologies that this has not happened sooner on my end.

**Comment by wenkesj** [comment]
@sibelius I need permissions to transfer this to react-native-community apparently.

**Comment by sibelius** [comment]
you can transfer to me, and then I can transfer there

**Comment by sibelius** [comment]
@wenkesj

can you give me publish access to npm https://www.npmjs.com/package/react-native-voice

here is my account https://www.npmjs.com/~sibelius

**Comment by Noitidart** [comment]
Thanks @sibelius for supporting such an important lib!!

**Comment by wenkesj** [comment]
@sibelius I will, thanks for helping out. Never would have imagined how far this library would go. Was such a fun project to begin with.

**Comment by sibelius** [comment]
0.3.0 on npm 

tks

**Comment by Damnum** [comment]
Thanks guys, really appreciate your effort. This project has helped us a lot on multiple apps.
