### ISSUE TITLE
Unable to build react-native-voice

### ISSUE THREAD

**Issue by jagadhishm87** [react-native-community/react-native-voice#190]
# Question
Build fails after i run the command react-native run-android. Error details are attached. Please help on this.
React-native version : 0.60

 
![image](https://user-images.githubusercontent.com/36987049/62456295-b9662500-b795-11e9-8f28-d515506e23a4.png)

**Comment by folofse** [comment]
React-native version 0.60.x uses Androidx, you can replace the import `android.support.annotation.NonNull` with `androidx.annotation.NonNull`

**Comment by jagadhishm87** [comment]
Thank you. its working after the above change.

**Comment by mikhailperemitko** [comment]
You can add this code into `app/build.gradle` file to resolve this issue automatically on every build. 
```
task fixReactNativeVoiceImport() {
    def libModule = file("../../node_modules/react-native-voice/android/src/main/java/com/wenkesj/voice/VoiceModule.java")
    def fixedText = libModule.text.replace('android.support.annotation.NonNull', 'androidx.annotation.NonNull')
    libModule.write(fixedText)
}

preBuild.dependsOn fixReactNativeVoiceImport
```
Hope it will be helpful for someone.

**Comment by JessyAngel07** [comment]
same issue persist 
![image (2)](https://github.com/react-native-voice/voice/assets/144873346/f7106194-9317-47fb-b869-8d16e1c98a18)
unable to build my app (react-native-community/voice) version 1.1.9
react-native version 0.72.7 @mykhailoperemitko @folofse @jagadhishm87 @kant @tdonia
