### ISSUE TITLE
Add readme for the sample application

### ISSUE THREAD

**Issue by YajanaRao** [react-native-community/react-native-voice#200]
# Question

Can you please add a readme for running the VoiceTest directory to explain the steps to run the application

**Comment by lfoliveir4** [comment]
have you seen the full example? 
https://github.com/react-native-community/react-native-voice/tree/master/VoiceTest

**Comment by lfoliveir4** [comment]
> # Question
> Can you please add a readme for running the VoiceTest directory to explain the steps to run the application

have you seen the full example? 
https://github.com/react-native-community/react-native-voice/tree/master/VoiceTest

**Comment by YajanaRao** [comment]
I have seen the example. Adding a readme with steps to execute would help.

**Comment by lfoliveir4** [comment]
@YajanaRao I will update Readme to get more objective how to use this lib.
