### ISSUE TITLE
Is this project maintained? 

### ISSUE THREAD

**Issue by Jithinqw** [react-native-community/react-native-voice#201]
Since the issues which are tagged as bug is not solved for a long time. Is this project maintained?

**Comment by mikey-passio** [comment]
Also interested in an answer to this.

**Comment by Jithinqw** [comment]
I guess this awkward silence answers my question :scream:

**Comment by MediaByte** [comment]
Suppose you’re right.

**Comment by lfoliveir4** [comment]
This project is being maintained. Starting today as a collaborator I will make the necessary updates and resolve the issues.
