### ISSUE TITLE
Speech recognition random freeze after start

### ISSUE THREAD

**Issue by Phasor1** [react-native-community/react-native-voice#202]
# Speech recognition random freeze after start
I'm using this library on android in an App always in foreground and potentially always in listening mode. Sometimes, after 5 minutes or more than one day of usage, the speech recognition stops listening without errors of any kind. It totally freeze after a successful recognition. Then is necessary to restart totally the App in order to let it listening again, but it doesn't work as solution.

## Environment info

React native info output:

```bash
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 8.52 GB / 15.89 GB
    Binaries:
      npm: 6.11.3 - C:\USERS\-DAVIDE-\APPDATA\ROAMING\NPM\npm.CMD
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4443003
```

Library version: 0.2.6

## Steps To Reproduce
Every time onSpeechResults() and onSpeechError() are triggered i call the Voice.start() method to keep the app listening for speech recognition.

**Comment by lfoliveir4** [comment]
@Phasor1 Did you solved your problem??

**Comment by Phasor1** [comment]
@lfoliveir4 yes, in a way. In the code, every time onSpeechResult and onSpeechError are triggered, i call Voice.cancel() and then Voice.start(). At first i saw that behaviour was manageable (after a crash, calling Voice.destroy() and then Voice.start(), restarts succesfully the speechRecognition for some hours, unlike it was happened before), and then, after a device reboot, i didn't see the speechRecognition crash again in that way.
I hope this explanation will be helpful, sorry for my english.

**Comment by Ngo-Tuan-Anh** [comment]
> @lfoliveir4 yes, in a way. In the code, every time onSpeechResult and onSpeechError are triggered, i call Voice.cancel() and then Voice.start(). At first i saw that behaviour was manageable (after a crash, calling Voice.destroy() and then Voice.start(), restarts succesfully the speechRecognition for some hours, unlike it was happened before), and then, after a device reboot, i didn't see the speechRecognition crash again in that way. I hope this explanation will be helpful, sorry for my english.

Hi Phasor1, how do you know when program is crashing? I log my Voice.onSpeechError() and gain a lot of "8/RecognitionService busy", "5/Client side error",and more. Then, my program is crash and does not recognize without error. Hope your answer as soon as possible

**Comment by Ngo-Tuan-Anh** [comment]
> > @lfoliveir4 yes, in a way. In the code, every time onSpeechResult and onSpeechError are triggered, i call Voice.cancel() and then Voice.start(). At first i saw that behaviour was manageable (after a crash, calling Voice.destroy() and then Voice.start(), restarts succesfully the speechRecognition for some hours, unlike it was happened before), and then, after a device reboot, i didn't see the speechRecognition crash again in that way. I hope this explanation will be helpful, sorry for my english.
> 
> Hi Phasor1, how do you know when program is crashing? I log my Voice.onSpeechError() and gain a lot of "8/RecognitionService busy", "5/Client side error",and more. Then, my program is crashed and does not recognize without error messages.  I hope I can get your answer as soon as possible. Thanks
