### ISSUE TITLE
What to remove beep sound in starting

### ISSUE THREAD

**Issue by vaibhgupta09** [react-native-community/react-native-voice#218]
# Feature Request

**Comment by lfoliveir4** [comment]
Your issue is not very understandable. Could you detail it better please?

**Comment by lfoliveir4** [comment]
> # Feature Request
> ## Why it is needed
> ## Possible implementation
> ### Code sample

@vaibhgupta09 Your issue is not very understandable. Could you detail it better please?

**Comment by vaibhgupta09** [comment]
hello @lfoliveir4 issue is resolved now thnks

**Comment by Somnus007** [comment]
Hi @vaibhgupta09 , how did you remove the beep sound?

**Comment by SolankiYogesh** [comment]
@vaibhgupta09  ?
